Abailon/i500 upstream v1
OpenAMP/libmetal pull request #139
Opened 2020-11-27 10:55 UTC by anobli

Hello,

This pull request intends to add support of the AI Processing Unit (APU), a dual core VP6 (Xtensa LX7 ISA).
This just adds the minimum required for Rpmsg to work on the Mediatek i500 SoC.
Because there many other SoC or microcontroller using the Xtensa architecture, the support of xtensa and APU have been separated.

To build libmetal, gcc 10 could be used. Still this requires few additional low level libraries so I could provided a prebuilt toolchain for people interested (until I could fully document how to rebuild one).
XCC (Cadence complier) could also be used but this requires more cmake options to be configured.

For testing libmetal, we are building and running test-metal-static.
Currently, we can only load it on a real target, using remoteproc which add some constraints (e.g a resource table is required).
In addition, there are no uart so all the log must go to a log buffer.
I may try to use qemu or Candence ISS instead of real target as this would be more convenient for CI.

Thanks,
Alexandre

2020-12-01 11:28 UTC, arnopo requested changes
Hello,

Few comments , i think the main point is the logs management.
Concerning CI I let @edmooring  responds, he is working on CI relying on QEMU for Xilinx platform.
Then we can also imagine a CI build test based on a github action using  XCC if your build environment is opensource. Something similar to existing github actions: https://github.com/OpenAMP/libmetal/tree/master/.github/actions/build_ci.

2020-12-03 10:09 UTC, anobli commented on lib/system/generic/i500_apu/sys.h
> +			 "r"(value), "r"(addr));
Actually, I will remove these functions because there are not used anymore.

2020-12-03 10:10 UTC, anobli commented on lib/processor/xtensa/CMakeLists.txt
> +# vim: expandtab:ts=2:sw=2:smartindent
What do you mean? Should I remove this line ?
I added it because this line was in many other cmake files.

2020-12-03 10:15 UTC, anobli commented on lib/system/generic/i500_apu/log.c
> +}
The main reason was to reduce code duplication between libmetal and openamp.
There are no USART available from the APU so the only to get log is the trace buffer.
I will see if I could move that somewhere else.

2020-12-03 11:27 UTC, arnopo commented on lib/processor/xtensa/CMakeLists.txt
> +# vim: expandtab:ts=2:sw=2:smartindent
yes please clean it. It should be cleaned in another place, but that is not the purpose of this PR.

2020-12-03 16:21 UTC, anobli commented on lib/processor/xtensa/atomic.h
> + * Copyright (c) 2015, Xilinx Inc. and Contributors. All rights reserved.
Fixed, thanks

2020-12-03 16:23 UTC, anobli commented on lib/system/generic/i500_apu/log.c
> +}
As you have suggested, I remove all of that!
Now, the libc will take care of using the log buffer by default when we use printf

2020-12-03 16:24 UTC, anobli commented on test/system/generic/irq.c
> -	return 0;
I will open a new Pr, thanks

2020-12-03 16:24 UTC, anobli commented on lib/system/generic/i500_apu/sys.h
> +int i500_vprintf(const char *p, va_list args);
I remove it since the libc implements printf

2020-12-03 16:26 UTC, anobli commented on lib/system/generic/i500_apu/log.c
> +
thanks for your comments
I have move that code to the libc and taken your comment in account

2020-12-03 16:28 UTC, anobli commented
I pushed a new branch. Thanks for you  feed back.

2020-12-10 14:03 UTC, arnopo requested changes
A few additional comments and questions, no major points.

2020-12-11 05:01 UTC, edmooring requested changes
I agree with @arnopo's comments.
Can you please add appropriate information to README.md describing the supported platforms and the addition of a new architecture, with pointers to the tools needed?
My CI work is primarily focused on ARM-based platform, so I'm not sure how this would fit in.

2020-12-14 08:56 UTC, anobli commented on test/system/generic/i500_apu/specs
> +
I have discovered the specs file by working on this project so I my understanding might be wrong.
I think I need to have to override some default options of the linker.
IIRC, the default options are to build a firmware that could run on an emulator.
I don't know if there is another to way to override those options but I will check.

2020-12-14 08:59 UTC, anobli commented on test/system/generic/i500_apu/ldscripts/elf32xtensa.x
> +/* Linker Script for default link */
This is legacy. Usually, the linker scripts for these platform are generated using a tool, which creates many files in ldscripts.
I kept only the linker script but I have not though to move it out from this folder.
I will do it.

2020-12-15 09:16 UTC, anobli commented on lib/system/generic/i500_apu/CMakeLists.txt
> +add_subdirectory(../xtensa_common ${CMAKE_CURRENT_BINARY_DIR}/../xtensa_common)
Hum, this is going to imply some changes in the libmetal code.
Currently, the cmake files and some headers expect the following hierarchy:
/lib/ssytem/generic/machine/

So to have a hierarchy like /familly/product/ I will have to change many files if I want to do it correctly (e.g do the same for all the supported machines).

Another intermediate options would be to replace PROJECT_MACHINE in CMakeLists.txt and some headers by another variable that would contains the good path, depending if we using the current hierarchy or the family/product hierarchy.

2020-12-15 10:24 UTC, arnopo commented on lib/system/generic/i500_apu/CMakeLists.txt
> +add_subdirectory(../xtensa_common ${CMAKE_CURRENT_BINARY_DIR}/../xtensa_common)
Your point is valid. As the hierarchy would have to be reworked. if @edmooring is Ok i propose to not update this  ( so similar to xlnx_common) and treat it is a separate point. The include hierarchy is something that as to be improved in libmetal

2021-01-28 10:48 UTC, anobli commented on test/system/generic/i500_apu/specs
> +
I spent some time to figure out how to do the same thing using gcc command line and I failed.
The closer result I got was making the command line really big and complex and it was still failing at link step.
The only other option we have if we want to get ride of this file is too do some changes in the toolchain itself.
If this OK for you, I would like to keep the spec file as it makes things simpler.

2021-01-29 08:41 UTC, arnopo commented on test/system/generic/i500_apu/specs
> +
Do you try to just add in cmake/platforms/i500-apu-generic.cmake?
`set(CMAKE_EXE_LINKER_FLAGS "-lc -lgloss -lminrt -lhandler-reset -lhandlers-board -lhal") `

Seems also that -lc and -lminrt are defined several times in the command line...

2023-10-16 00:24 UTC, closed without merging