openamp/libmatal: fix Non-zero offsets to null pointers
OpenAMP/libmetal pull request #165
Opened 2021-07-13 02:53 UTC by xiaoxiang781216

leads to ASAN errors
libmetal/lib/system/nuttx/io.c:78:9: runtime error: applying non-zero offset 4124131344 to null pointer
metal/io.h:136:3: runtime error: applying non-zero offset 4124131440 to null pointer
metal/io.h:136:3: runtime error: applying non-zero offset 4124131440 to null pointer
metal/io.h:136:3: runtime error: applying non-zero offset 4124131440 to null pointer
metal/io.h:136:3: runtime error: applying non-zero offset 4124131552 to null pointer
metal/io.h:136:3: runtime error: applying non-zero offset 4124132000 to null pointer
==15484==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0xffd3c000; bottom 0xf3437000; size: 0x0c905000 (210784256)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189

2021-07-14 06:08 UTC, edmooring requested changes
Overall, this looks good. Please update the commit message to include the text in the description of the pull request. 

Also 'libmatal' -> 'libmetal' in the first line.

2021-08-03 07:03 UTC, xiaoxiang781216 commented
Done, @edmooring

2021-08-10 10:04 UTC, arnopo approved these changes
Look good to me, 
Please could you  precise in the commit message that the errors have be reported by ASAN
Thanks!

2021-08-10 10:17 UTC, xiaoxiang781216 commented
Done.

2021-08-10 14:46 UTC, arnopo commented
CI test failed is linked to the CI environment and fixed her: https://github.com/OpenAMP/libmetal/pull/167
The compliance check failed, but it is related to a build log that exceeds 80 characters per line, acceptable to ignore this complain.

2021-08-10 21:00 UTC, edmooring approved these changes
Looks good to me.

2021-08-12 12:36 UTC, merged