zynqmp_r5: replace Xil_SetMPURegion with Xil_MemMap
OpenAMP/libmetal pull request #218
Opened 2022-08-27 00:51 UTC by kernelchuk

The metal_machine_io_mem_map() used to call Xil_SetMPURegion directly
and could get into an infinite loop. Replace the faulty code in
metal_machine_io_mem_map() with Xil_MemMap() call and assert it succeeds.

Signed-off-by: Sergei Korneichuk <sergei.korneichuk@amd.com>
---
fixes: 51e08c67556474762257a825fc92cf8dbd302388

2022-08-30 20:28 UTC, TanmayShah-xilinx commented
@arnopo, @edmooring 

```
#51: FILE: lib/system/freertos/zynqmp_r5/sys.c:69:
[23](https://github.com/OpenAMP/libmetal/runs/8046721200?check_suite_focus=true#step:6:24)
+	void *__attribute__((unused)) physaddr = Xil_MemMap(pa, size, flags);
[24](https://github.com/OpenAMP/libmetal/runs/8046721200?check_suite_focus=true#step:6:25)
```

Above warning is false positive I believe. As it is not function definition, but Xil_MemMap is function use.
However, would you recommend not to use __attribute__() in the same line where variable is initialized?
I don't see any downside of it, but I may be wrong.

2022-08-31 07:40 UTC, arnopo commented
> @arnopo, @edmooring
> 
> ```
> #51: FILE: lib/system/freertos/zynqmp_r5/sys.c:69:
> [23](https://github.com/OpenAMP/libmetal/runs/8046721200?check_suite_focus=true#step:6:24)
> +	void *__attribute__((unused)) physaddr = Xil_MemMap(pa, size, flags);
> [24](https://github.com/OpenAMP/libmetal/runs/8046721200?check_suite_focus=true#step:6:25)
> ```
> 
> Above warning is false positive I believe. As it is not function definition, but Xil_MemMap is function use. However, would you recommend not to use **attribute**() in the same line where variable is initialized? I don't see any downside of it, but I may be wrong.

Following code seeems not generate this  false positive:
```
void *metal_machine_io_mem_map(void *va, metal_phys_addr_t pa,
			       size_t size, unsigned int flags)
{
	void *__attribute__((unused)) physaddr;

	physaddr = Xil_MemMap(pa, size, flags);
	metal_assert(physaddr == (void *)pa);
	return va;
}
```

2022-09-01 09:45 UTC, kernelchuk commented
Thank you Arnaud, I fixed the code, I should have done it when it was flagged before sending the first PR. Not sure why Zephyr build fails. Any hints ?

2022-09-01 11:57 UTC, arnopo commented
> Thank you Arnaud, I fixed the code, I should have done it when it was flagged before sending the first PR. Not sure why Zephyr build fails. Any hints ?

No idea yet, probably a problem in the IC.  I tried to rerun the action without success. I need to look deeper. Just ignore the check for now.

2022-09-01 12:11 UTC, arnopo commented
@bentheredonethat
Any feedback on this PR?
Thanks

2022-09-01 18:07 UTC, bentheredonethat commented
@arnopo  i am in support of this patch. AMD BSP provides this so we should leverage as proposed by Sergei.

2022-09-01 22:47 UTC, edmooring reviewed
Looks good to me.

2022-09-01 22:48 UTC, edmooring approved these changes

2022-09-09 16:27 UTC, arnopo commented
Please could you rebase on main to rerun the Ci? CI issue should be fixed in https://github.com/OpenAMP/libmetal/pull/219

2022-09-09 18:53 UTC, kernelchuk commented
Hi Arnaud, Ed,
I have about 30 commits with bug fixes in our AMD/Xilinx internal repos and I'd like to upstream them.
I can
  1.  Create PRs for each of them
  2.  Combine all or some of them in a one PR
What is your preferred method of up-steaming these commits?

2022-09-13 16:57 UTC, arnopo requested changes
just an update for the copyright else LGTM

2022-09-13 16:57 UTC, arnopo commented on lib/system/freertos/zynqmp_r5/sys.c
> + * Copyright (c) 2016 - 2022, Xilinx Inc. and Contributors. All rights reserved.
nitpicking : just replace 2016 by 2022

2022-09-13 16:57 UTC, arnopo commented on lib/system/generic/zynqmp_r5/sys.c
> + * Copyright (c) 2016 - 2022, Xilinx Inc. and Contributors. All rights reserved.
same here

2022-09-16 03:05 UTC, edmooring commented
Agreed on the 30 commits. As a rough guideline, combining commits that don't overlap and only affect one file each is fine. A multi-file commit probably deserves its own PR.

2022-09-21 15:20 UTC, arnopo approved these changes

2022-09-21 15:23 UTC, merged