FreeRTOS Avoid mem mapping in MPU for region mapped
OpenAMP/libmetal pull request #284
Opened 2024-02-01 14:29 UTC by rajimoha

FreeRTOS patch for Avoiding memory mapping in MPU config table for region that are already mapped by bsp and no change in attribute property Note: this is a temp fix, need a more robust solution to avoid issues coming up later

2024-02-10 09:02 UTC, edmooring requested changes
Need to fix the formatting issues as well as address my comment.

2024-02-10 09:02 UTC, edmooring commented on lib/system/freertos/xlnx/sys.c
> +			(mpu_config[cnt].flags & XMPU_VALID_REGION); cnt++){
This loop will terminate early if the MPU register mappings are sparse. If registers 0, 1, and 3 have valid regions, but 2 does not, 3 will be skipped. 

I think this part of the test should be moved into the loop as an if() continue statement.

2024-02-15 11:29 UTC, rajimoha commented
@edmooring changes done.. ping for review

2024-02-16 21:01 UTC, edmooring approved these changes
Looks good to go.

2024-02-19 08:33 UTC, arnopo requested changes
commit message format to fix

2024-02-19 13:10 UTC, arnopo approved these changes

2024-02-19 13:11 UTC, merged