zynq: Remove support for Zynq-7000 SoC
OpenAMP/libmetal pull request #303
Opened 2024-08-02 09:39 UTC by rajimoha

Remove support for Zynq-7000 SoC, changes are
1. Remove Zynq7 tool chain support
2. Makefile changes to remove zynq7

Reasons to remove:
1. Support for Zynq-7000 has ended
2. Removing redundant or unmaintained code
3. Reduce technical debt carried by OpenAMP team
4. very few customer using openamp on Zynq-7000 SoC

For using Zynq-7000 SoC support last working and tested version is (v2023.10)
https://github.com/OpenAMP/libmetal/tree/v2023.10

2024-08-06 15:32 UTC, wmamills commented
@tnmysh please add a section to top level README for deprecated platforms, add zynq-7000 to it and list the last version with support.

Have you looked at the CI failure?

2024-08-06 15:33 UTC, wmamills requested changes
Add readme section as described in PR comment.

Fix or explain CI failure

2024-08-06 15:39 UTC, tnmysh commented
I haven't started reviews on this yet. I am yet to send notification on mailing lists about deprecation of zynq7000.

2024-08-22 05:04 UTC, edmooring approved these changes
Looks good to go.

2024-09-03 20:41 UTC, tnmysh commented
@rajimoha Could you rebase on latest tip of tree?

Also, Please add deprecated platforms related information in README file here:
https://github.com/OpenAMP/libmetal/edit/main/README.md

2024-09-03 21:02 UTC, tnmysh commented
@wmamills I think https://github.com/OpenAMP/libmetal/pull/307 is needed, for CI to pass for this PR.

Zephyr failure, is probably not done by this PR. Do you have any opinion if we should merge this PR before #307  ?

Also, There is same PR in open-amp repo that remove zynq-7000 support. That should be merged first, and after that this change should be merged.

2024-09-03 21:05 UTC, tnmysh commented
> * Support for Zynq-7000 has ended

This is not really true. Please remove this from commit message.

Zynq7000 platform is suported, only open-amp stack will be discontinued.

2024-09-04 07:03 UTC, arnopo commented
> @wmamills I think #307 is needed, for CI to pass for this PR.
> 
> Zephyr failure, is probably not done by this PR. Do you have any opinion if we should merge this PR before #307 ?
> 
> Also, There is same PR in open-amp repo that remove zynq-7000 support. That should be merged first, and after that this change should be merged.

rebasing on the main branch should solve the CI issue since the PR #306 has been merged

2024-09-06 21:28 UTC, tnmysh commented
> Add readme section as described in PR comment.
> 
> Fix or explain CI failure

Done.

2024-09-09 07:19 UTC, arnopo approved these changes

2024-09-16 06:37 UTC, rajimoha commented
@wmamills anything further in this request

2024-10-08 07:31 UTC, xiaoxiang781216 approved these changes

2024-10-11 20:50 UTC, tnmysh commented
I think this PR can be merged.

2024-10-11 20:50 UTC, tnmysh approved these changes

2024-10-14 09:51 UTC, merged