nuttx/mutex.h: bug fix, change MUTEX_INITIALIZER to NXMUTEX_INITIALIZER
OpenAMP/libmetal pull request #321
Opened 2024-10-29 15:32 UTC by CV-Bowen

Now nuttx use NXMUTEX_INITIALIZER to initialize the mutex, so updated.

2024-11-04 03:47 UTC, CV-Bowen commented
@arnopo Hi, could you review this PR?

2024-11-06 15:07 UTC, tnmysh approved these changes

2024-11-07 07:56 UTC, arnopo requested changes
- Please fix commit message subject format 
lib: system: nuttx:  change MUTEX_INITIALIZER to NXMUTEX_INITIALIZER
- fix `uses` typo

2024-11-21 01:46 UTC, CV-Bowen commented
@arnopo Thanks, done, please review again.

2024-11-21 02:49 UTC, edmooring approved these changes
Looks good to go.

2024-11-26 12:54 UTC, arnopo approved these changes

2024-11-26 12:54 UTC, merged